## Exemples Algebra

In [2]:
import numpy as np #importem la llibreria

#### Exemples de vectors (array)

In [3]:
v=np.array([1,0,0])
u=np.array([0,-2,0])

In [4]:
print (u)
print (v)

[ 0 -2  0]
[1 0 0]


Operacións amb vectors (suma, resta, producte escalar i vectorial)

In [6]:
w1=u+v #suma vectors
print(w1)
w2=u-v #resta vectors
print(w2)

[ 1 -2  0]
[-1 -2  0]


In [8]:
a=np.dot(u,v) #producte escalar
print(a)

0


In [10]:
b=np.cross(u,v) #producte vectorial
print(b)

[0 0 2]


#### Exemples amb Matrius

In [12]:
A=np.array([[2,4],[1,3]])
print (A)

[[2 4]
 [1 3]]


In [13]:
e=A[0,1] #si volem accedir a cada element es fa d'aquesta manera (el 0 es la primera fila i l'1 es la segona columna)
print(e)

4


v=A[0,:] #els dos punts es un comodi, no li dono index a aquest segon valor, vol dir que agafi totes les columnes de la fila 0
print (v)

In [20]:
u=A[:,1] #li estem dient que agafi totes les files de la segona columna
print(u)

[4 3]


Valors i vectors propis

In [22]:
A=np.array([[2,2],[1,3]])
print (A)

[[2 2]
 [1 3]]


In [23]:
Valors,Vectors=np.linalg.eig(A) #Amb això calculem valors i vectors propis, pero sense ordenar.
print("Valors propis",Valors)
print("Vectors propis",Vectors)

Valors propis [1. 4.]
Vectors propis [[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]


In [25]:
u=Vectors[:,0] #Per treure el primer vector propi fem això, ja que no el volem en format de matriu
print(u)

[-0.89442719  0.4472136 ]


In [26]:
v=Vectors[:,1] #Així s'aconsegueix el segon vector propi
print(v)

[-0.70710678 -0.70710678]


Comprovem que efectivament son vectors propis

In [31]:
z=np.dot(A,u)#La mateixa variant per multiplicar vectors serveix per multiplicar matrius
print(z)

[-0.89442719  0.4472136 ]


In [32]:
z2=np.dot(A,v)
print(z2)

[-2.82842712 -2.82842712]


Altres exemples de matrius utils

In [33]:
A=np.zeros([3,3]) #Creem una matriu que sigui 0
print(A)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
